(() => {
  const URL='https://qmhyeotvbktdilrudwys.supabase.co';
  const KEY='sb_publishable_Yin9aHOMDRYJ0PsuMloVlQ_q8M7iReT';
  const sb=window.supabase?.createClient?.(URL,KEY); let user=null,currentId=null;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const numberFromMoney=v=>{if(typeof v==='number')return v;const s=String(v||'').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null};
  function cloudPayload(){const c=clone(data);c.heroImage='';c.extras=(c.extras||[]).map(e=>({...e,image:''}));return c}
  function setCloudState(text,ok=false){let x=document.querySelector('#pecQuoteCloudState');if(x){x.textContent=text;x.classList.toggle('ok',ok)}}
  function addUI(){
    const editor=document.querySelector('.editor'); if(!editor||document.querySelector('#pecQuoteCloud'))return;
    const box=document.createElement('details');box.id='pecQuoteCloud';box.open=true;box.innerHTML=`<summary>pec Manager • Nuvem</summary><div class="fields"><div id="pecQuoteCloudState" class="pm-cloud-state">Verificando conta…</div><div class="pm-cloud-actions"><button type="button" class="primary" id="pecQuoteSave">Salvar online</button><button type="button" class="secondary" id="pecQuoteNew">Novo</button></div><div class="pm-cloud-actions"><button type="button" class="secondary" id="pecQuoteContract">Gerar contrato</button><button type="button" class="secondary" id="pecQuoteAgenda">Adicionar à agenda</button></div><div id="pecQuoteHistory" class="pm-history"></div></div>`;
    const first=editor.querySelector('details'); first?editor.insertBefore(box,first):editor.appendChild(box);
    const st=document.createElement('style');st.textContent=`.pm-cloud-state{font-size:10px;color:#aaa;padding:7px 9px;border-radius:9px;background:rgba(255,255,255,.05)}.pm-cloud-state.ok{color:#73dca5}.pm-cloud-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.pm-history{display:grid;gap:6px;max-height:190px;overflow:auto}.pm-hist{border:1px solid #393939;background:#111;color:#fff;border-radius:9px;padding:9px;text-align:left;cursor:pointer}.pm-hist b{display:block;font-size:11px}.pm-hist span{font-size:9px;color:#aaa}html[data-pm-theme="light"] body[data-theme] .pm-hist{background:#f5f6f5;color:#171918;border-color:#d4d8d5}html[data-pm-theme="light"] body[data-theme] .pm-cloud-state{background:#eef0ee;color:#666}.pm-hist-empty{font-size:10px;color:#aaa;padding:6px 0}`;document.head.appendChild(st);
    document.querySelector('#pecQuoteSave').onclick=saveOnline;document.querySelector('#pecQuoteNew').onclick=newQuote;document.querySelector('#pecQuoteContract').onclick=toContract;document.querySelector('#pecQuoteAgenda').onclick=toAgenda;
  }
  function newQuote(){currentId=null;data=clone(DEFAULT);data.issueDate=new Date().toISOString().slice(0,10);fillFixed();renderScopeEditor();renderExtrasEditor();renderAll();setCloudState('Novo orçamento • ainda não salvo',!!user)}
  async function saveOnline(){if(!user){alert('Entre na conta pela Agenda para salvar na nuvem.');return}const p=cloudPayload();currentId=currentId||`q-${Date.now()}`;const total=p.investmentMode==='perItem'?(p.scope||[]).reduce((s,x)=>s+(numberFromMoney(x.value)||0),0):numberFromMoney(p.total);const row={id:currentId,user_id:user.id,client_name:p.client||'',event_date:p.eventDate||null,status:'draft',total_value:total,payload:{...p,_managerId:currentId},updated_at:new Date().toISOString()};setCloudState('Salvando…');const{error}=await sb.from('quotes').upsert(row,{onConflict:'id'});if(error){console.error(error);setCloudState('Erro ao salvar');alert('Não foi possível salvar o orçamento na nuvem.')}else{setCloudState('Salvo na nuvem ✓',true);loadHistory()}}
  async function loadHistory(){if(!user)return;const{data:rows,error}=await sb.from('quotes').select('*').order('updated_at',{ascending:false}).limit(30);if(error)return;const el=document.querySelector('#pecQuoteHistory');if(!el)return;el.innerHTML=(rows||[]).map((r,i)=>`<button type="button" class="pm-hist" data-i="${i}"><b>${esc(r.client_name||'Sem cliente')}</b><span>${r.event_date?dateBR(r.event_date):'Sem data'} • ${r.total_value!=null?Number(r.total_value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}</span></button>`).join('')||'<div class="pm-hist-empty">Nenhum orçamento salvo.</div>';el.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>loadRow(rows[Number(b.dataset.i)]))}
  function loadRow(row){const p=row.payload||{};currentId=row.id;data={...clone(DEFAULT),...p,heroImage:'',scope:Array.isArray(p.scope)?p.scope.map(normalizeScope):clone(DEFAULT.scope),extras:Array.isArray(p.extras)?p.extras.map(e=>normalizeExtra({...e,image:''})):clone(DEFAULT.extras)};fillFixed();renderScopeEditor();renderExtrasEditor();renderAll();setCloudState('Orçamento carregado da nuvem ✓',true);window.scrollTo({top:0,behavior:'smooth'})}
  function toContract(){const p=cloudPayload();localStorage.setItem('pec-manager-contract-seed',JSON.stringify(p));location.href='./contratos.html?from=quote'}
  async function toAgenda(){if(!user){alert('Entre na conta pela Agenda.');return}if(!data.eventDate){alert('Informe a data do evento.');return}if(!confirm('Adicionar este orçamento à agenda?'))return;const tm=/^(\d{1,2}):(\d{2})/.exec(String(data.time||''));const hh=tm?`${String(tm[1]).padStart(2,'0')}:${tm[2]}`:null;const id=`quote-${currentId||Date.now()}`;const row={id,user_id:user.id,title:data.client?`Evento — ${data.client}`:'Evento',date:data.eventDate,time_type:hh?'time':'tbd',time_value:hh?`${hh}:00`:null,place:[data.venue,data.city].filter(Boolean).join(', '),notes:`Cliente: ${data.client||'—'} • Orçamento`,completed:false,completed_at:null,updated_at:new Date().toISOString()};const{error}=await sb.from('events').upsert(row,{onConflict:'id'});alert(error?'Não foi possível adicionar.':'Evento adicionado à agenda ✓')}
  async function init(){addUI();if(!sb){setCloudState('Nuvem indisponível');return}const{data:s}=await sb.auth.getSession();user=s.session?.user||null;setCloudState(user?`Conectado • ${user.email}`:'Modo local • entre pela Agenda',!!user);if(user)loadHistory();if(new URLSearchParams(location.search).get('new')==='1')newQuote()}
  setTimeout(init,0);
})();
